### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by maddie-jones** [jpclark6/i-wet-my-plants#6]
As a registered user.
When I visit all pages except the welcome page I see a navbar and I should see a "Logout" button.
When I press the button I should be logged out and redirected to the welcome page.
I should se a message "You successfully logged out".

**Comment by maddyg91** [comment]
As a registered user. 
When I visit all pages except the welcome page I see a navbar and I should see a "Logout" button.
When I press the button I should be logged out and redirected to the welcome page. 
I should se a message "You successfully logged out".
